name: terraform-ci

on:
  pull_request:
  push:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envdir: [envs/dev, envs/prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
          terraform_wrapper: false

      - name: Terraform fmt (repo)
        run: terraform fmt -check -recursive
      
      - name: Terraform init (no backend)
        working-directory: ${{ matrix.envdir }}
        run: terraform init -backend=false 

      - name: Terraform validate
        working-directory: ${{ matrix.envdir }}
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0

      - name: TFLint init
        run: tflint --init

      - name: TFLint
        run: tflint -f compact

  plan-dev:
    runs-on: ubuntu-latest
    needs: lint-validate
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
          terraform_wrapper: false

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::210006515605:role/GitHubActionsTerraformPlan
          aws-region: eu-north-1

      - name: Terraform init (no backend)
        working-directory: envs/dev
        run: terraform init -backend=false

      - name: Terraform plan (dev, no refresh)
        working-directory: envs/dev
        run: terraform plan -no-color -refresh=false
